{
 "title": "DAQ Profiled Processes",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "CU + JDW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process instances - CU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:5132"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Number of mono processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:5153"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Number of JLigier processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Process instances - JDW",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:6548"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": {
      "filter": "Number of JDataWriter processes"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:6569"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Number of JLigier processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:6590"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Number of mono processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage - CU",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7553"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7574"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Process JLigier memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage trend - CU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:5244"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:5265"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Process JLigier memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage - JDW",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7694"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": {
      "filter": "Process JDataWriter memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7715"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Process JLigier memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7736"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage trend JDW",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)",
       "$$hashKey": "object:5919"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": {
      "filter": "Process JDataWriter memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)",
       "$$hashKey": "object:5940"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Process JLigier memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)",
       "$$hashKey": "object:5961"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage - CU ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:5693"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:5714"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Process JLigier cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage trend - CU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:5592"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:5613"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Process JLigier cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage - JDW",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6047"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Process JDataWriter cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6068"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Process JLigier cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6089"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage trend JDW",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:6132"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Process JDataWriter cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:6153"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:6174"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Process JLigier cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM available - CU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Available memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Swap - CU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk space available on / - CU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-cu-03" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM available - JDW",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Available memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Swap - JDW",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk space available on /var/km3net/nfsshare - JDW",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-jdw-01" },
     "item": {
      "filter": "Free disk space on /var/km3net/nfsshare/data (percentage)"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "DataQueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Process instances DQ-05",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:1004"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Number of DataQueue processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:1025"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Number of monrouter2 processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:1046"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Number of mono processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Process instances DQ-06",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "$$hashKey": "object:1763",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Number of DataQueue processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "$$hashKey": "object:1784",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Number of monrouter2 processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "$$hashKey": "object:1805",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Number of mono processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage - DQ-05",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6629"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": {
      "filter": "Process DataQueue memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6650"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": {
      "filter": "Process monrouter2 memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6671"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage trend DQ-05",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "$$hashKey": "object:2227",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": {
      "filter": "Process DataQueue memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "$$hashKey": "object:2248",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": {
      "filter": "Process monrouter2 memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "$$hashKey": "object:2269",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage - DQ-06",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6710"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": {
      "filter": "Process DataQueue memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6731"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": {
      "filter": "Process monrouter2 memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6752"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage trend DQ-06",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "$$hashKey": "object:2599",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": {
      "filter": "Process DataQueue memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "$$hashKey": "object:2620",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": {
      "filter": "Process monrouter2 memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "$$hashKey": "object:2641",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage - DQ-05",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6791"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Process DataQueue cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6812"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Process monrouter2 cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6833"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage trend DQ-05",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:3228"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Process DataQueue cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:3249"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Process monrouter2 cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:3270"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage - DQ-06",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6872"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process DataQueue cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6893"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process monrouter2 cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:6914"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage trend DQ-06",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:1113"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process ADF cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:1134"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process DataQueue cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:1155"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process JDataFilter cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:1176"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process JDataWriter cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:1197"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process monrouter2 cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:1239"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM available - DQ05",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Available memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-05" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM available - DQ-06",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Available memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-dq-06" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "DataFilters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Process instances ODF-01",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:2630"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": {
      "filter": "Number of JDataFilter processes"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:2651"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": { "filter": "Number of mono processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Process instances ODF-02",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:2130"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": {
      "filter": "Number of JDataFilter processes"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:2151"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": { "filter": "Number of mono processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Process instances ADF-01",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:7001"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Number of ADF processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Number (\\w+) (\\w+) (\\w+)/",
        "$2"
       ],
       "text": "replaceAlias(/Number (\\w+) (\\w+) (\\w+)/, $2)",
       "$$hashKey": "object:7022"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Number of mono processes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage - ODF-01",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7055"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": { "filter": "Process JDataFilter memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7076"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": { "filter": "Process mono memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage trend ODF-01",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 3, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)",
       "$$hashKey": "object:1323"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": {
      "filter": "Process JDataFilter memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)",
       "$$hashKey": "object:1344"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage - ODF-02",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7109"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": { "filter": "Process JDataFilter memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7130"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": { "filter": "Process mono memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage trend ODF-02",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)",
       "$$hashKey": "object:2908"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": {
      "filter": "Process JDataFilter memory percent"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)",
       "$$hashKey": "object:2929"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage - ADF-01",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7163"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Process ADF memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7184"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Process mono memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage trend ADF-01",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)",
       "$$hashKey": "object:1647"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Process ADF memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) memory percent/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) memory percent/, $1)",
       "$$hashKey": "object:1668"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage - ODF-01",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7217"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": { "filter": "Process JDataFilter cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7238"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": { "filter": "Process mono memory percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage trend ODF-01",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 3, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:3828"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": { "filter": "Process JDataFilter cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:3849"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage - ODF-02",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7271"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": { "filter": "Process JDataFilter cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7292"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage trend ODF-02",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:3354"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": { "filter": "Process JDataFilter cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:3375"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage - ADF-01",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7325"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Process ADF cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) (\\w+) (\\w+)/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) (\\w+) (\\w+)/, $1)",
       "$$hashKey": "object:7346"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU usage trend ADF-01",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:3063"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Process ADF cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Profiled process" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Process (\\w+) cpu util/",
        "$1"
       ],
       "text": "replaceAlias(/Process (\\w+) cpu util/, $1)",
       "$$hashKey": "object:3084"
      }
     ],
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Process mono cpu util" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM available - ODF-01",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": { "filter": "Available memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Swap - ODF-01",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-01" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM available - ODF-02",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": { "filter": "Available memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Swap - ODF-02",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-odf-02" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM available - ADF-01",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Available memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Swap - ADF-01",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "KM3NeT_DAQ" },
     "host": { "filter": "arca-adf-01" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}